sudo: false
language: java
cache:
   apt: true
   directories:
    - /home/travis/opt
    - ./sumo-0.22.0
before_install:
    - sh ./script/ci/installSumo.sh
    
after_failure:
    - cat TrafficMASTests/output/*
